server:
  port: 8080
spring:
  application:
    name: my-app

  h2:
    console:
      enabled: true
      path: /h2
    datasource:
      url: jdbc:h2:mem:contacts;PASSWORD=mypass;USER=myuser
      driverClassName: org.h2.Driver


