#server:
#  port: 8080
#spring:
#  application:
#   name: my-app
#   h2:
#     console:
#       enabled: true
#       path: /h2
#   datasource:
#     url: jdbc:h2:mem:contacts
#     user: root
#     password: root
#     driverClassName: org.h2.Driver



